fos_rest:
    view:
        view_response_listener: force
    routing_loader:
        default_format: json
    body_converter: 
        enabled: true
        validate: true
    param_fetcher_listener: true
