masters:
  type: rest
  resource: App\Controller\MastersController

companies:
  type: rest
  resource: App\Controller\CompaniesController

creditcards:
  type: rest
  resource: App\Controller\CreditcardsController


